service:
  name: ebs

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
